{% set version = "6.6.1" %}

package:
  name: qt6-graphs
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/qtgraphs-everywhere-src-{{ version }}.tar.xz
  md5: e9d93ecc1daee2d32deb2bfac281e6dd

build:
  number: 0
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage('qt6-graphs', max_pin='x.x') }}

  # needs osx sdk 12.3, to fix once rendered in the feedstock through build_config.yaml
  skip: true  # [osx]

requirements:
  build:
    - cmake
    - ninja
    - perl
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - qt6-main {{ version }}  # [build_platform != target_platform]
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
  host:
    - qt6-main {{ version }}

test:
  requires:
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
    - cmake
    - ninja
  source_files:
    - examples/
  commands:
    {% set qt_libs = ["Graphs"] %}
    {% for each_qt_lib in qt_libs %}
    - test -d $PREFIX/include/qt6/Qt{{ each_qt_lib }}  # [unix]
    - test -f $PREFIX/lib/libQt6{{ each_qt_lib }}${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\qt6\\Qt{{ each_qt_lib }} exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\Qt6{{ each_qt_lib }}.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\Qt6{{ each_qt_lib }}.dll exit 1  # [win]
    {% endfor %}

about:
  home: http://qt-project.org
  license: GPL-3.0-only
  license_file: LICENSES/GPL-3.0-only.txt
  summary: Qt is a cross-platform application and UI framework.
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: http://doc.qt.io/
  dev_url: https://github.com/qt/qtgraphs

extra:
  recipe-maintainers:
    - jschueller
  feedstock-name: qt-graphs
